### ISSUE TITLE
Free Tab Option

### ISSUE THREAD

**Issue by RussW** [micker/mod_dashboard#10]
When adding a "Free Tab", the "Free Button" column displays "Joomla\CMS\Form\Form::getInstance() could not load file"

Joomla! : v3.9.4

**Comment by micker** [comment]
strange can you say me module version ?

**Comment by micker** [comment]
i think i found solution
https://github.com/micker/mod_dashboard/commit/a3ebd64cbe9c955837cdbf1b3fec2c6a0fa238ab
can you confirm it ?

**Comment by RussW** [comment]
This appears to be resolved now, thank you
