### ISSUE TITLE
Module Class Suffix not honoured

### ISSUE THREAD

**Issue by RussW** [micker/mod_dashboard#12]
If you enter a "Module Class Suffix" in the "Advance" tab, it is not honoured on the module output (allowing module specific CSS customisation)

**Comment by micker** [comment]
that is good with my last commit ?
https://github.com/micker/mod_dashboard/commit/592a96b0e076d71d38a01922a63f04f7ac32f820

**Comment by RussW** [comment]
this appears to be working now, thank you
