### ISSUE TITLE
Tabs disappear on click mouse

### ISSUE THREAD

**Issue by iorbita** [micker/mod_dashboard#14]
Hello,
Tabs disappear on click mouse. The problem occurs when Advanced Module Manager by Regular Labs is enabled. The problem was not fixed?

Thank you

**Comment by micker** [comment]
normalement c'est régler avec la derniere version ... apres j'ai pas re tester verifie les css si ils sont bien charger

**Comment by iorbita** [comment]
quels css?

**Comment by micker** [comment]
tu pourrais me donner un accès ?

**Comment by iorbita** [comment]
je t'envoie ça où?

**Comment by micker** [comment]
yannick@com3elles.com
