### ISSUE TITLE
Icon Selection Before Save

### ISSUE THREAD

**Issue by RussW** [micker/mod_dashboard#2]
Disable or hide icon selection before saving, otherwise if clicked returns to main admin page

**Comment by micker** [comment]
hello it a limitation about joomla subform ... need to save before
https://github.com/micker/mod_joomadmin/commit/f5843d982a7fa60e0724e2004074619dfdfd0839
... difficult to find a turn arround it some for select2js

**Comment by web54** [comment]
perharps you should have one enabled by default ?

**Comment by web54** [comment]
fix it with css : 
button#jform_params__free_button__free_button0__free_button__free_buttonX__iconbutton-wrapper:empty {
    display: none;
