### ISSUE TITLE
Language strings missing

### ISSUE THREAD

**Issue by RussW** [micker/mod_dashboard#3]
Several language strings missing for tooltips

**Comment by micker** [comment]
Hello can you guide me ? in module admin ? in display ?
can you send me string ?

**Comment by RussW** [comment]
Apologies the delay, using the latest release;

Tabs General Config - All strings missing
Custom Tabs - last 2x strings missing
Tabs Administration - 3x string missing

**Comment by micker** [comment]
very strange can you provide a screenshot ?

**Comment by RussW** [comment]
all language strings are showing now
