### ISSUE TITLE
cpanel position layout broken

### ISSUE THREAD

**Issue by RussW** [micker/mod_dashboard#4]
There appears to be one too many closing divs ( </div> ) in the cpanel position layout forcing any existing modules assigned to "cpanel" to drop below and outside of the span9 (right-hand column)

**Comment by micker** [comment]
ahhh thanks for testing i will investigate

**Comment by micker** [comment]
i think closed by https://github.com/micker/mod_joomadmin/commit/509cf2eca7829e4d68965534e926125aa5a6052b
can you confirm it ?

**Comment by RussW** [comment]
I've finally had time to look at this again and for my installations it appears that there is an erroneous unused div after the tabs that breaks the admin page layout if other modules are displayed below the dashboard.

around line 361 in default.php
</div>
	
</div>

**Comment by micker** [comment]
hello can you test whith update with master branch ?

**Comment by RussW** [comment]
Hi there, I still end up commenting the 2nd <div> on line 278 otherwise the overall page layout is broken with the com_dashboard extending over the sidebar to full width and forcing the lower joomla! modules to do the same. (I don't use your inbuilt information blocks under the basic tab display)

But, it appears that no-one see's this issue, so I'll close and continue to comment out the extra div in my case through an override.

**Comment by micker** [comment]
hello thanks for your return i need to check this
